name: Publish Docker image
on:
  push:
    tags:
      - 'v*'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            docker.pkg.github.com/londonhackspace/kube-auth-handler/server:${GITHUB_REF##*/}
  build_client:
    name: Build Clients
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      - name: build stuff
        working-directory: ./auth-client
        run: |
          env GOOS=linux GOARCH=amd64 go build -o ldap-kube-auth_linux_amd64
          env GOOS=linux GOARCH=arm go build -o ldap-kube-auth_linux_arm
          env GOOS=linux GOARCH=arm64 go build -o ldap-kube-auth_linux_arm64
          env GOOS=darwin GOARCH=amd64 go build -o ldap-kube-auth_macos_amd64
          env GOOS=darwin GOARCH=arm64 go build -o ldap-kube-auth_macos_arm64
          env GOOS=windows GOARCH=amd64 go build -o ldap-kube-auth_windows_amd64.exe
      - name: Release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
        run: gh release create ${GITHUB_REF##*/} ldap-kube-auth_*